name: release npm package
on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run lint

  build_windows:
    needs:
      - lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run make
      - shell: bash
        run: |
          cp -r ./out/make ./out/build_windows
      - uses: actions/upload-artifact@v3
        with:
          name: dist-windows
          path: ./out/build_windows

  build_linux:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run make
      - run: cp -r ./out/make ./out/build_linux
      - uses: actions/upload-artifact@v3
        with:
          name: dist-linux
          path: ./out/build_linux

  build_macos:
    needs:
      - lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run make
      - run: cp -r ./out/make ./out/build_macos
      - uses: actions/upload-artifact@v3
        with:
          name: dist-macos
          path: ./out/build_macos

  release:
    needs:
      - build_linux
      - build_windows
      - build_macos
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y tree
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: actions/download-artifact@v3
      - run: tree
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
